### ISSUE TITLE
client returning nil time

### ISSUE THREAD

**Issue by Dfenniak** [danieljacobarcher/omniauth-square#4]
Hey, I'm not sure if anyone is still monitoring this repo, but I've ran into an issue with it, and I'm not quite sure what the answer is.

It seems that in the code I've linked below ['expires_at'] is being set to nil by fetch_access_token. Which is resulting in :bomb:. My Issue here is, should we be expecting an expires_at and is the client sending us lousy data, or is this broken and should it be able to handle a nil 'expires_at'.

```
        def build_access_token
          parsed_response = fetch_access_token
  
        parsed_response['expires_at'] = Time.parse(parsed_response['expires_at']).to_i
          parsed_response.merge!(deep_symbolize(options.auth_token_params))
          
          connect_client = client.dup
          connect_client.site = options.client_options.connect_site
          ::OAuth2::AccessToken.from_hash(connect_client, parsed_response)
        end
```

**Comment by danieljacobarcher** [comment]
@Dfenniak I'll look into it!

**Comment by Dfenniak** [comment]
Thanks so much! I wasn't expecting such a quick response, I'll also keep investigating on my end!

**Comment by danieljacobarcher** [comment]
@rzane Any suggestions?

**Comment by Dfenniak** [comment]
I'm currently just testing out not parsing nils and seeing if it blows up elsewhere, or if this is valid:

```
parsed_response['expires_at'] = Time.parse(parsed_response['expires_at']).to_i if parsed_response['expires_at'].present?
```

**Comment by Dfenniak** [comment]
locally it doesn't seem to blow up if I just add that check, I'm gonna make a pull request and leave it to you to deliberate

**Comment by rzane** [comment]
Hi @Dfenniak, I'm using this in production and I haven't encountered time when expires_at was nil. Could dump `response.parsed` from line 51 of ib/omniauth/strategies/square.rb and show it to us (without the token, of course).

According to Square's documentation (http://docs.connect.squareup.com/#post-token), it looks like a POST to /oauth/token returns an expires_at. If I were you, I'd be very weary about skipping that expires_at. You'll probably want to save that in your database so you know when your token needs to be refreshed.

**Comment by Dfenniak** [comment]
Thanks for looking in to this, I'll grab that right now

**Comment by Dfenniak** [comment]
So I actually can't seem to reproduce the error, I don't know if there was a temporary issue with their API or what the story is, I'm going to close this issue and the pull request, sorry for wasting your time and thanks for the help guys

**Comment by rzane** [comment]
No problem. Thanks for trying to help!
